export const PRODUCTS = [
  {
    id: 1,
    name: 'Banarasi Silk Saree',
    hindi: 'बनारसी रेशम साड़ी',
    category: 'saree',
    price: 4500,
    originalPrice: 6000,
    stock: 15,
    description: 'Handwoven Banarasi silk saree with intricate gold zari work. A timeless piece for weddings and celebrations.',
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&q=80',
    badge: 'Bestseller',
  },
  {
    id: 2,
    name: 'Kanjivaram Silk Saree',
    hindi: 'कांजीवरम साड़ी',
    category: 'saree',
    price: 5500,
    originalPrice: 7500,
    stock: 8,
    description: 'Pure Kanjivaram silk with traditional temple border design. Rich colors and heavy zari make it perfect for special occasions.',
    image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600&q=80',
    badge: 'Premium',
  },
  {
    id: 3,
    name: 'Chanderi Cotton Saree',
    hindi: 'चंदेरी सूती साड़ी',
    category: 'saree',
    price: 1800,
    originalPrice: 2500,
    stock: 25,
    description: 'Lightweight Chanderi cotton saree with delicate floral prints. Perfect for daily wear and office occasions.',
    image: 'https://images.unsplash.com/photo-1616627547584-bf28cee262db?w=600&q=80',
    badge: 'New',
  },
  {
    id: 4,
    name: 'Embroidered Anarkali Suit',
    hindi: 'अनारकली सूट',
    category: 'suit',
    price: 3200,
    originalPrice: 4500,
    stock: 12,
    description: 'Elegant embroidered Anarkali suit with dupatta. Intricate thread work on georgette fabric for a royal look.',
    image: 'https://images.unsplash.com/photo-1594938298603-c8148c4b4266?w=600&q=80',
    badge: 'Trending',
  },
  {
    id: 5,
    name: 'Punjabi Patiala Suit',
    hindi: 'पटियाला सूट',
    category: 'suit',
    price: 1500,
    originalPrice: 2200,
    stock: 20,
    description: 'Vibrant Patiala suit with phulkari embroidery. Comfortable and stylish for festive occasions.',
    image: 'https://images.unsplash.com/photo-1585914924626-15adac1e6402?w=600&q=80',
    badge: null,
  },
  {
    id: 6,
    name: 'Lucknowi Chikankari Suit',
    hindi: 'लखनवी चिकनकारी सूट',
    category: 'suit',
    price: 2800,
    originalPrice: 3800,
    stock: 10,
    description: 'Authentic Lucknowi chikankari on pure cotton fabric. Hand-embroidered with traditional motifs by skilled artisans.',
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&q=80',
    badge: 'Handcrafted',
  },
  {
    id: 7,
    name: 'Kolhapuri Chappals',
    hindi: 'कोल्हापुरी चप्पल',
    category: 'sandals',
    price: 850,
    originalPrice: 1200,
    stock: 30,
    description: 'Genuine leather Kolhapuri chappals with traditional hand-stitching. Durable and comfortable for everyday wear.',
    image: 'https://images.unsplash.com/photo-1603487742131-4160ec999306?w=600&q=80',
    badge: 'Handmade',
  },
  {
    id: 8,
    name: 'Mojari Embroidered Jutis',
    hindi: 'मोजारी जूती',
    category: 'sandals',
    price: 1200,
    originalPrice: 1800,
    stock: 18,
    description: 'Rajasthani mojari with mirror work and embroidery. Perfect complement to ethnic wear.',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80',
    badge: null,
  },
  {
    id: 9,
    name: 'Zardozi Clutch Purse',
    hindi: 'जरदोज़ी क्लच',
    category: 'purse',
    price: 1400,
    originalPrice: 2000,
    stock: 22,
    description: 'Handcrafted zardozi clutch with gold thread embroidery. Perfect for weddings and festive occasions.',
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&q=80',
    badge: 'Festive',
  },
  {
    id: 10,
    name: 'Rajasthani Potli Bag',
    hindi: 'राजस्थानी पोटली',
    category: 'purse',
    price: 750,
    originalPrice: 1100,
    stock: 35,
    description: 'Traditional Rajasthani potli bag with mirror work and tassels. A beautiful ethnic accessory.',
    image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600&q=80',
    badge: 'Popular',
  },
  {
    id: 11,
    name: 'Oxidised Silver Jewellery Set',
    hindi: 'ऑक्सीडाइज्ड आभूषण',
    category: 'jewellery',
    price: 950,
    originalPrice: 1400,
    stock: 40,
    description: 'Traditional oxidised silver jewellery set with earrings, necklace and bangles. Perfect for ethnic wear.',
    image: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&q=80',
    badge: null,
  },
  {
    id: 12,
    name: 'Kundan Bridal Jewellery Set',
    hindi: 'कुंदन आभूषण सेट',
    category: 'jewellery',
    price: 3500,
    originalPrice: 5000,
    stock: 5,
    description: 'Exquisite Kundan bridal jewellery set with meenakari work. A stunning ensemble for the modern bride.',
    image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&q=80',
    badge: 'Bridal',
  },
];

export const CATEGORIES = [
  { id: 'all', label: 'All Items', hindi: 'सभी' },
  { id: 'saree', label: 'Sarees', hindi: 'साड़ियाँ' },
  { id: 'suit', label: 'Suits', hindi: 'सूट' },
  { id: 'sandals', label: 'Sandals', hindi: 'चप्पल' },
  { id: 'purse', label: 'Purses', hindi: 'पर्स' },
  { id: 'jewellery', label: 'Jewellery', hindi: 'आभूषण' },
];
